version: '2'
services:
  jh20200404-app:
    image: jh20200404
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jh20200404-postgresql:5432/jh20200404
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jh20200404-postgresql:
    extends:
      file: postgresql.yml
      service: jh20200404-postgresql
